version: '3.8'
services:
  user-service:
    build: .
    image: user-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/management_db
      - SPRING_DATASOURCE_USERNAME=usr_bci
      - SPRING_DATASOURCE_PASSWORD=usr_bciPwd
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: management_db
      POSTGRES_USER: usr_bci
      POSTGRES_PASSWORD: usr_bciPwd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: