config:
    jwtExpiration: 86400000
    secretKeyJWT: WTQkW3hZc2lnc1Rva2VuRm9ySldUSE1TMTIzNDU2Nzg5MA==
    regex:
        email: "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Za-z]{2,}$"
        password: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"
spring:
    application:
        name: user-service
    datasource:
        driverClassName: org.h2.Driver
        password: 12345678910
        url: jdbc:h2:mem:management_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    hikari:
        auto-commit: true
        minimum-idle: 5
        maximum-pool-size: 10
        idle-timeout: 30000
        max-lifetime: 1800000
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
    h2:
        console:
            enabled: true
            path: /h2-console

server:
    port: 8080

# Configuración de Actuator para monitoreo y administración
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,env

# Configuración de Swagger/OpenAPI
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html

logging:
    level:
        root: INFO
        org.springframework: INFO
        com.example.registration: DEBUG

---
# Configuración para ambiente de producción (perfil prod con PostgreSQL)
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://db:5432/management_db
        username: postgres
        password: postgres
        hikari:
            auto-commit: true
            minimum-idle: 5
            maximum-pool-size: 10
            idle-timeout: 30000
            max-lifetime: 1800000
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: false

logging:
    level:
        root: INFO
        org.springframework: INFO
        com.example.registration: INFO